@startuml
start
:获取数据库中所有有效的循环任务;
:过滤出有效的循环任务（今天可添加）;
:获取今天的所有任务;
if (判断是否应该添加循环任务) then (应该)
    :添加任务;
endif
:进入空闲提醒流程;
if (今天是否处于工作时间) then (是)
    if (任务是否15分钟内结束?) then (是)
        :本地通知,提醒任务即将结束;
        stop
    else (否)
        stop
    endif
else (否)
    if (判断未来两小时是否有任务) then (有)
        if (判断 15 分钟是否有临近任务) then (有)
            :本地通知,提醒新增任务;
        else (无)
            stop
        endif
    endif
endif
stop
@enduml
